version: 2.1
jobs:
  compile:
   docker:
      - image: zycromerz/kerneldocker:latest
   steps:
      - run:
          command: |
            git clone https://$githubKey@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git -b $CIRCLE_BRANCH dumpper --depth=1
            cd dumpper
            bash ./run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
