name: Building New Kernel

on: [push]

env:
  GIT_SECRET: ${{ secrets.GIT_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TZ: Asia/Jakarta
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    defaults:
      run:
        shell: bash

    timeout-minutes: 360

    strategy:

        fail-fast: false

        matrix:
          config:
            # - file: blank
            # - link: 'https://bigota.d.miui.com/V12.5.6.0.RGGIDXM/miui_BEGONIAIDGlobal_V12.5.6.0.RGGIDXM_e5599068e6_11.0.zip'
            #   filename: 'miui_BEGONIAIDGlobal_V12.5.6.0.RGGIDXM_e5599068e6_11.0.zip'
            #   type: 'url' # url / gd
            - link: '1SVMX06XzXP6gCBQmUzE1cCjlUOl7pyvt'
              filename: 'Infinix-Note-40-X6853-V530DevT.zip'
              type: 'gd' # url / gd

    name: run-${{ matrix.config.filename }}

    runs-on: ubuntu-latest

    # container:
    #   image: zycromerz/kerneldocker:v4

    steps:

      - name: "Cleanup Environment"
        uses: rokibhasansagar/slimhub_actions@main

      - name: Checkout
        uses: actions/checkout@v3

      - name: dump roms
        run: |
          chmod +x dumpyara.sh
          chmod +x run.sh
          chmod +x setup.sh
          ./setup.sh
          ./run.sh "${{ matrix.config.link }}" "${{ matrix.config.filename }}" "${{ matrix.config.type }}"
